#!/usr/bin/env python3


"""Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(n):
    """Return the n'th value in Fibonacci sequence starting with 1, 2, ..."""
    if n < 3:
        return n
    return fibonacci(n-1) + fibonacci(n-2)

i = 1
fib = fibonacci(i)
sum = 0
while fib <= 4e6:
    i += 1
    fib = fibonacci(i)
    if fib % 2 == 0:
        sum += fib

print(sum)
